39번 이슈에 대한 코드 수정
Team-MansuMugang/mansumugang-backend pull request #40
Opened 2024-07-20 06:31 UTC by JSH0905

#39 이슈에 대한 코드 수정을 완료하였습니다.

2024-07-20 07:47 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/controller/user/PatientLocationController.java
> +            @AuthenticationPrincipal Protector protector,
Protector가 아닌 Patient로 접근했을때 오류가 발생하지않나요?

2024-07-20 08:19 UTC, minnnisu requested changes
코멘트 작성한 부분 반영 부탁드립니다.

2024-07-20 08:19 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationInquiryRequestDto.java
> +    private Long patientId;
patientId를 PathVariable으로 받도록 다시 바꿀 수 있을까요?
(/api/location/user/{patient_Id})를 말하는겁니다.)
계속 요구사항을 바꿔서 미안합니다ㅠㅠ

2024-07-20 08:19 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
> +    public Patient validatePatient(Long userId) {
변수명을 userId -> patientId로 바꾸면 좋을 거 같네요

2024-07-20 08:19 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
> +        Protector foundProtector = validateProtector(protector.getId()); // 현재 로그인 되있는 보호자의 정보를 검증하는게 의미가 있나(?)
이것 또한 그리고 protector.getId()에서 protector가 null일 경우 500 에러가 발생할 수 있고 개인적으로 validateProtector함수에는 현재 로직 대신 protector가 null인지 검증하는 로직이 필요할 거 같습니다.

2024-07-20 08:19 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
> +    private void validateRelation(Protector foundProtector, Patient foundPatient) {
해당 함수의 로직을 아래와 같이 바꿀 수 있을 거 같아요.
```
private void checkUserIsProtectorOfPatient(Protector protector, Patient patient){
    // TODO: equals, hashcode 구현
    if(!patient.getProtector().getUsername().equals(protector.getUsername())) {
        throw new CustomErrorException(ErrorType.AccessDeniedError);
    }
}
```
Protector 엔티티에서 equals, hashcode를 오버라이딩하면 조금 더 좋은 코드를 작성할 수 있을 거 같은데 저의 JPA 지식이 부족하네요.
나중에 좀 더 공부해서 같이 수정해봐요.

2024-07-22 03:04 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
> +        Patient foundPatient = validatePatient(patient.getId());
이 부분은 저도 중복된다고 생각해서 굳이 한번더 검증을 해야하나? 이런 생각을 계속하고있었습니다. 결국은 팀장님이랑 같은 생각이었던 것 같습니다.

2024-07-22 03:06 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/controller/user/PatientLocationController.java
> +            @AuthenticationPrincipal Protector protector,
환자 위치를 받는 경우가 보호자가 서비스에 로그인했을 경우라고만 생각해서 환자로 접근할 상황이 없다고 생각해서 그런 판단을 한 것 같습니다.

2024-07-22 03:08 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/controller/user/PatientLocationController.java
> +            @AuthenticationPrincipal Protector protector,
또 질문이 하나 더 있는데, 위의 경우라면 saveUserLocation 메서드 또한 Patient가 아닌 User로 받아야할까요?`

2024-07-22 03:10 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationInquiryRequestDto.java
> +    private Long patientId;
괜찮습니다. 다만 결국은 왜 경로변수로 patient_id를 받으려고 판단했는지 이유를 알려주실 수 있나요?

2024-07-22 03:15 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
> +    public Patient validatePatient(Long userId) {
확인했습니다.

2024-07-22 03:17 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
> +    public Patient validatePatient(Long userId) {
아래 validateProtector 메서드의 변수명 또한 userId -> protectorId로 변경하였습니다.

2024-07-22 03:23 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
> +    private void validateRelation(Protector foundProtector, Patient foundPatient) {
넵 알겠습니다~

2024-07-22 03:41 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/controller/user/PatientLocationController.java
> +            @AuthenticationPrincipal Protector protector,
> 환자 위치를 받는 경우가 보호자가 서비스에 로그인했을 경우라고만 생각해서 환자로 접근할 상황이 없다고 생각해서 그런 판단을 한 것 같습니다.

해당 URL로 어느 누가 접근 할지 알 수 없기 때문에 최대한 다양한 경우의 수를 염두해두고 로직을 짜는게 중요하다고 생각합니다.
일단은 컨트롤러에서는 User로 받고 서비스단에서 유저를 걸러내도록 짜주시면 감사하겠습니다.
그리고 다음 주 쯤에 같이 리펙토링을 하면서 로직을 고쳐나가 봅시다.

2024-07-22 03:41 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/controller/user/PatientLocationController.java
> +            @AuthenticationPrincipal Protector protector,
> 또 질문이 하나 더 있는데, 위의 경우라면 saveUserLocation 메서드 또한 Patient가 아닌 User로 받아야할까요?`

위의 코멘트와 동일합니다.

2024-07-22 03:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/dto/user/location/PatientLocationInquiryRequestDto.java
> +    private Long patientId;
잘 설계된 URL 요소 중 하나가 리소스를 식별할 수 있는 URL이라고 생각합니다.
patient_Id을 path variable를 이용하여 나타내면 어떤 사용자의 위치를 나타내는지 명확히 알 수 있다고 생각되어 변경을 요청드렸습니다.

2024-07-22 04:11 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
> +        Protector foundProtector = validateProtector(protector.getId()); // 현재 로그인 되있는 보호자의 정보를 검증하는게 의미가 있나(?)
확인했습니다.

2024-07-22 04:20 UTC, JSH0905 commented
코드 수정완료하였습니다.  다만 수정된 코드에서 컨트롤러단에서는 User객체로 받고 서비스단에서 실제 Protector 또는 Patient 객체인지 확인하고 예외를 발생시키면된다는 팀장님의 말씀이 지켜졌는지 잘 모르겠습니다. 한번 확인 부탁드니다.

2024-07-23 00:45 UTC, minnnisu requested changes
수정사항 하나만 반영 부탁드립니다.

2024-07-23 00:45 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
여기에 User가 null인지 검증하는 로직 하나가 필요할 거 같습니다.

2024-07-23 01:11 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/service/user/UserLocationService.java
넵 확인했습니다.

2024-07-23 01:12 UTC, minnnisu reviewed
승인합니다.

2024-07-23 01:12 UTC, minnnisu approved these changes
승인합니다.

2024-07-23 01:12 UTC, merged