46번 이슈에 대한 일부 코드 구현입니다.
Team-MansuMugang/mansumugang-backend pull request #54
Opened 2024-08-02 06:36 UTC by JSH0905

세부 내용은 다음과 같습니다.
- 음성 녹음 관련 기능 중 저장, 조회에 대한 코드 구현  
- 환자 위치 정보 관련 기능 중 조회에 대해서 추가 작업

#46

2024-08-02 08:46 UTC, minnnisu requested changes
전반적으로 수정해야할 부분이 많아보입니다.
이전 코드리뷰에서 반영못한 부분까지 코멘트를 작성했으니 반영부탁드립니다.
또한 API별로 서로 다른 DTO 클래스를 작성하여 사용해주시면 감사하겠습니다.

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
> +                                                    @RequestPart(name = "audio", required = false) MultipartFile recordFile
음성파일을 저장하는 것이 주목적인 API이기 때문에 `required = false`를 `true`로 바꾸는 것이 좋을듯 합니다.

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
> +    public RecordSave.SavedInfo saveRecord(User user, MultipartFile recordFile){
코드를 다음과 같이 수정하고 테스트 진행 부탁드립니다.
```
public RecordSave.SavedInfo saveRecord(User user, MultipartFile recordFile){
    Patient validPatient = validatePatient(user);

    if (recordFile == null) {
        throw new CustomErrorException();
    }

    try {
        String recordFileName = fileService.saveRecordFile(recordFile);
        Long recordDuration = fileService.getRecordDuration(recordFileName);
        Record newRecord = recordRepository.save(Record.of(validPatient, recordFileName, recordDuration));
        log.info("저장된 녹음파일에 대한 정보 DB에 저장 완료");
        return RecordSave.SavedInfo.getInfo(newRecord);
    } catch (Exception e) {
        throw new CustomErrorException(ErrorType.InternalServerError);
    }

}
```

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
> +        List<RecordInquiry.Dto> recordInquiryDtos = getDtos(foundAllRecords);
`getDtos` 메소드의 작업은 `RecordInquiry.Dto`에서 이뤄지도록 아래 함수를 수정해주세요.
`RecordInquiry.Dto.fromEntity(foundAllRecords)`

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
> +        return RecordInquiry.Response.createNewResponse(recordInquiryDtos);
`RecordInquiry.Response.createNewResponse` 메소드는 Controller단으로 빼주세요

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
> +                                                                            @PathVariable("patient_id") Long patientId
`getAllRecordsWithId`를 `getAllRecordsByPatientId`로 바꿔주세요

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/controller/record/RecordController.java
> +        List<RecordInquiry.Response> allRecords = recordService.getOnePatientsRecords(user, patientId);
`getOnePatientsRecords`를 `getAllRecordsByPatientId`로 바꿔주세요

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/record/RecordService.java
> +        List<RecordInquiry.Dto> recordInquiryDtos = getDtos(foundAllRecords);
`getDtos` 메소드도 Dto로 책임을 넘겨주세요

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/repository/RecordRepository.java
> +    List<Record> findByPatient_idOrderByCreatedAtDesc(long patient_id);
`findByPatient_idOrderByCreatedAtDesc`를 `findByPatientIdOrderByCreatedAtDesc`로 바꿔주세요.

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
> +        private String savedPath;
일단 `savedPath`을 `audioApiUrlPrefix`로 변경해주세요.
`audioApiUrlPrefix`와 `recordFileName`을 합쳐 하나의 오디오 파일 주소를 만들면 좋을 거 같습니다.
http://localhost:8080/records/ + a23dakdkslenei11.mp3 이런식으로요.

application-local.yaml을 다음과 같이 작성합니다.
```
file:
  upload:
    image:
      api: http://localhost:8080/records/
      path: src/main/resources/static/records
```

이후 `audioApiUrlPrefix`를 다음과 같이 사용하여 `file.upload.audio.api`의 값을 연결시켜주세요
```
@Value("${file.upload.image.api}") 
private String audioApiUrlPrefix
```

이런식으로 프론트엔드에게 api 주소 prefix를 전달하여 오디오 파일에 접근할 수 있게 구현하면 좋을 거 같습니다.

2024-08-02 08:46 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/dto/record/RecordInquiry.java
> +        private String savedPath;
여기서도 `savedPath`를 `audioApiUrlPrefix`로 변경해주세요.

2024-08-02 09:01 UTC, minnnisu commented on src/main/java/org/mansumugang/mansumugang_service/service/location/UserLocationService.java
> +        return Optional.ofNullable(userLocationRepository.findByPatientWithinTimeRange(foundPatient, inquiryStartTime, inquiryEndTime))
`findByPatientWithinTimeRange`에서 null이 발생할 가능성이 없다면 괜찮다고 생각합니다.
그리고 Optional.ofNullable를 쓴 다른 코드도 본 거 같은데 그것 또한 null이 발생할 가능성이 없다면 수정 부탁드립니다.

2024-08-02 09:02 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/service/location/UserLocationService.java
> +        return Optional.ofNullable(userLocationRepository.findByPatientWithinTimeRange(foundPatient, inquiryStartTime, inquiryEndTime))
넵 알겠습니다~

2024-08-02 09:06 UTC, JSH0905 commented on src/main/java/org/mansumugang/mansumugang_service/service/location/UserLocationService.java
> +        return PatientLocationResponseDto.fromDtoList(foundPatient, patientLocationDtos);
확인했습니다.

2024-08-04 10:59 UTC, minnnisu approved these changes
승인합니다.

2024-08-04 10:59 UTC, merged